import React from 'react';
import Head from 'next/head';
import Dashboard from './dashboard';

function Home() {
  return (
    <div>
      <Head>
        <title>Decentralized NFTs 🇵🇭</title>
        <meta name='description' content='Generated by Anton Guinto' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Dashboard />
      </main>
    </div>
  );
}

export default Home;
