import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = function Home() {
  return (
    <div>
      <Head>
        <title>Template</title>
        <meta name='description' content='Generated by Anton Guinto' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex flex-col justify-center items-center min-h-screen'>
        <h1 className='font-bold text-[4rem]'>Hello, Template.</h1>
        <h1 className='text-xl font-bold'>
          NextJS, Typescript, Airbnb Eslint TS, Prettier, Husky, TailwindCSS
        </h1>
        <h1 className='text-xl mt-1'>To get started, run, npm install</h1>
        <h1 className='mt-2'>
          Template by{' '}
          <span>
            <a
              href='http://antonguinto.com'
              target='_blank'
              rel='noopener noreferrer'
              className='text-violet-600 font-bold'
            >
              Anton Guinto.
            </a>
          </span>
        </h1>
      </main>
    </div>
  );
};

export default Home;
