import React from 'react';
import Head from 'next/head';
import Dashboard from '../components/dashboard';
import Sidebar from '../components/sidebar';

function Home() {
  return (
    <div>
      <Head>
        <title>Decentralized NFTs 🇵🇭</title>
        <meta name='description' content='Generated by Anton Guinto' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex h-screen'>
        <div className='flex flex-col relative md:flex-row md:overflow-hidden'>
          <Sidebar />
          <Dashboard />
        </div>
      </main>
    </div>
  );
}

export default Home;
